version: '3.8'

services:
  # 1. Сервис API машинного обучения (FastAPI)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recsys_api
    ports:
      - "8000:8000"
    restart: always

  # 2. Сервис Telegram-бота
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recsys_bot
    # Переопределяем дефолтную команду Dockerfile на запуск бота
    command: python bot/main.py
    environment:
      # Внутри сети Docker бот обращаемся к API по имени контейнера "api"
      - API_URL=http://api:8000/recommend
      - BOT_TOKEN=${BOT_TOKEN}  # Берёт переменную из локального файла .env
    depends_on:
      - api
    restart: always